[character]
success_symbol = "[](bold green) "
error_symbol = "[](bold red) "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[dotnet]
symbol = " "
format = "[$symbol($version )(什$tfm)]($style)"

[git_branch]
symbol = ""
style = "red"
format = '[$symbol $branch ]($style)'

[git_metrics]
disabled = false
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
symbol = ""

[git_status]
disabled = false
format = "([$all_status$ahead_behind]($style) )"
modified = "פֿ "
staged = " "
deleted = "✘ "
stashed = " "
untracked = " "