
# Brewfile

# Make sure we have all the taps we need before beginning.
tap 'homebrew/boneyard'
tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/php'
tap 'caskroom/cask'
tap 'caskroom/versions'

# Brews
brew 'git'
brew 'bash-completion'
brew 'zsh'
brew 'zsh-completions'

# Casks
cask_args appdir: '/Applications'
cask 'hyper'
cask 'iterm2'
cask 'dr-unarchiver'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'gitkraken'
cask 'powershell'

brew cleanup